# Generated by Django 2.1.5 on 2019-01-31 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('file_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='ui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.UI'),
        ),
    ]
