# Generated by Django 2.1.5 on 2019-02-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ui',
            name='img',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
