# Generated by Django 2.1.5 on 2019-02-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_ui_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_ok',
            field=models.BooleanField(default=False),
        ),
    ]
