# Generated by Django 2.2 on 2019-02-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_auto_20190202_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ui',
            old_name='user',
            new_name='name',
        ),
    ]
