# Generated by Django 2.1.5 on 2019-02-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_auto_20190213_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='score',
            field=models.CharField(default='jn', max_length=20),
        ),
    ]
