# Generated by Django 2.1.5 on 2019-02-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_uploadfile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='result',
            field=models.CharField(default='실패', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
