# Generated by Django 2.1.5 on 2019-02-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0009_auto_20190217_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='result',
            field=models.CharField(default='Fail', max_length=250),
        ),
    ]
